const MockDocumentData = [
  {
    docNo: "RP_2N_LP_13M_DRC_1.0_A",
    version: "1.0_A",
    title: "RP_2N_LP_13M_DRC",
    group: 'DRC_Command_File',
    partner: "Siemens",
  },
  {
    docNo: "RP_2N_LP_DRC_LOGIC_1.0_A",
    version: "1.0_A",
    title: "RP_2N_LP_DRC_LOGIC",
    group: 'Design_Rule',
    partner: "Synopsys",
  },
  {
    docNo: "RP_2N_LP_OASIS_Layer_map_CDN_1.0_A",
    version: "1.0_A",
    title: "RP_2N_LP_OASIS_Layer_map_CDN",
    group: "OASIS_Layer_Usage_Description",
    partner: "Cadence",
  },
  {
    docNo: "RP_2N_GN_DRC_RF_1.0r_B",
    version: "1.0r_B",
    title: "RP_2N_GN_DRC_RF",
    group: 'Design_Rule',
    partner: "Synopsys",
  },
  {
    docNo: "RP_2N_LP_DRC_LOGIC_1.1_A",
    version: "1.1_A",
    title: "RP_2N_LP_DRC_LOGIC",
    group: 'Design_Rule',
    partner: "Cadence",
  },
  {
    docNo: "RP_2N_GN_DRC_RF_1.2_B",
    version: "1.2_B",
    title: "RP_2N_GN_DRC_RF",
    group: 'Design_Rule',
    partner: "Synopsys",
  },
  {
    docNo: "RP_2N_LP_10M_DRC_1.1_A",
    version: "1.1_A",
    title: "RP_2N_LP_10M_DRC",
    group: 'DRC_Command_File',
    partner: "Synopsys",
  },
  {
    docNo: "RP_2N_GN_11M_DRC_RF_1.0_B",
    version: "1.0_B",
    title: "RP_2N_GN_11M_DRC_RF",
    group: 'DRC_Command_File',
    partner: "Siemens",
  },
  {
    docNo: "RP_2N_LP_OASIS_Layer_map_SYN_1.0_B",
    version: "1.0_B",
    title: "RP_2N_LP_OASIS_Layer_map_SYN",
    group: "OASIS_Layer_Usage_Description",
    partner: "Synopsys",
  },
  {
    docNo: "RP_2N_LP_OASIS_Layer_map_SN_1.0_C",
    version: "1.0_C",
    title: "RP_2N_LP_OASIS_Layer_map_SN",
    group: "OASIS_Layer_Usage_Description",
    partner: "Siemens",
  },
  {
    docNo: "RP_2N_GN_OASIS_Layer_map_CDN_1.1_A",
    version: "1.1_A",
    title: "RP_2N_GN_OASIS_Layer_map_CDN",
    group: "OASIS_Layer_Usage_Description",
    partner: "Cadence",
  },
  {
    docNo: "RP_2N_GN_15M_DRC_RF_1.2_B",
    version: "1.2_B",
    title: "RP_2N_GN_15M_DRC_RF",
    group: 'DRC_Command_File',
    partner: "Cadence",
  },
];

export default MockDocumentData;