const MockDocumentData = [
    {
      docNo: "A-B11-01",
      version: "2.0",
      title: "Document AAA",
      group: "Design Rule",
      partner: "Cadence",
    },
    {
      docNo: "A-F25-03",
      version: "1.0",
      title: "Document BBB",
      group: "Design Rule",
      partner: "Magma",
    },
    {
      docNo: "A-B11-01",
      version: "2.0",
      title: "Document AAA",
      group: "Design Rule",
      partner: "Cadence",
    },
    {
      docNo: "A-F25-03",
      version: "1.0",
      title: "Document BBB",
      group: "Design Rule",
      partner: "Magma",
    },
    {
      docNo: "A-B11-01",
      version: "2.0",
      title: "Document AAA",
      group: "Design Rule",
      partner: "Cadence",
    },
    {
      docNo: "A-F25-03",
      version: "1.0",
      title: "Document BBB",
      group: "Design Rule",
      partner: "Magma",
    },
    {
      docNo: "A-F25-03",
      version: "1.0",
      title: "Document BBB",
      group: "Design Rule",
      partner: "Magma",
    },
    {
      docNo: "A-B11-01",
      version: "2.0",
      title: "Document AAA",
      group: "Design Rule",
      partner: "Cadence",
    },
    {
      docNo: "A-F25-03",
      version: "1.0",
      title: "Document BBB",
      group: "Design Rule",
      partner: "Magma",
    },
    {
      docNo: "A-B11-01",
      version: "2.0",
      title: "Document AAA",
      group: "Design Rule",
      partner: "Cadence",
    },
    {
      docNo: "A-F25-03",
      version: "1.0",
      title: "Document BBB",
      group: "Design Rule",
      partner: "Magma",
    },
    {
      docNo: "A-B11-01",
      version: "2.0",
      title: "Document AAA",
      group: "Design Rule",
      partner: "Cadence",
    },
  ];

export default MockDocumentData;